### ISSUE TITLE
Pause button inline display style "inline" causses issue

### ISSUE THREAD

**Issue by jsakas** [Accessible360/accessible-slick#23]
When the button is visible I want it to be `display: flex`.

The inline style overrides this, I think there should just be no style added like it is for the default.

The only work around right now is to do this:

```scss
.slick-pause-icon, 
.slick-play-icon {
  display: flex;
}

.slick-pause-icon, 
.slick-play-icon {
  &[style='display: inline;'] {
    display: flex !important;
  }
}
```
